logging:
  level:
    org.springframework: ERROR
    org.mfh114.dtog: DEBUG

spring:
  profiles:
    active: dev
  main:
    banner-mode: "off"

application:
 name: Data Transfer Object Generator (DTOG)
 configRoot: /config
 jdbcLibRoot: /jdbclib
 pluginsRoot: /plugins

